name: 'ng2_if_for'
version: 0.0.1
description: An absolute bare-bones web app.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular2: ">=2.0.0-alpha.22 <3.0.0"
  browser: '>=0.10.0 <0.11.0'

transformers:
  - angular2
